### ISSUE TITLE
Bench run results are missing between runnings

### ISSUE THREAD

**Issue by PalumboN** [tesonep/benchy#33]
Now all bench results are in one file `benchy-runs.csv`.

The problem is that this file is overridden on each use of Bench (each call to `./runBenchs.sh` for example).

It is problematic, I would like to run different benchmarks and then compare them. Now I need to rename the file and merge the data after (so, the idea to have all the data in one place is not happening).

Also, the rest of the files in the run (`stdout` and `stderr`) are appended, not overridden.

**Comment by guillep** [comment]
Fixed in https://github.com/tesonep/benchy/pull/34, right? I'll close it, reopen if needed
